permissions:
  contents: write

name: Generate Snake Animation

on:
  schedule: # Runs once a day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake.svg
      - uses: Platane/snk@v3
        with:
          github_user_name: KhushiShs
          outputs: |
            dist/snake.svg

      # Step 2: Push the generated file to the output branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
